export const categoryOptions = [
	{ label: "Accessories", text: "Accessories", value: "accessories" },
	{ label: "Automotive", text: "Automotive", value: "automotive" },
	{ label: "Bags", text: "Bags", value: "bags" },
	{ label: "Dresses", text: "Dresses", value: "dresses" },
	{ label: "Fragrances", text: "Fragrances", value: "fragrances" },
	{ label: "Furniture", text: "Furniture", value: "furniture" },
	{ label: "Groceries", text: "Groceries", value: "groceries" },
	{ label: "Home Decoration", text: "Home Decoration", value: "home-decoration" },
	{ label: "Jewellery", text: "Jewellery", value: "jewellery" },
	{ label: "Laptops", text: "Laptops", value: "laptops" },
	{ label: "Motorcycle", text: "Motorcycle", value: "motorcycle" },
	{ label: "Shirts", text: "Shirts", value: "shirts" },
	{ label: "Shoes", text: "Shoes", value: "shoes" },
	{ label: "Skincare", text: "Skincare", value: "skincare" },
	{ label: "Smartphones", text: "Smartphones", value: "smartphones" },
	{ label: "Sunglasses", text: "Sunglasses", value: "sunglasses" },
	{ label: "Tops", text: "Tops", value: "tops" },
	{ label: "Watches", text: "Watches", value: "watches" },
];
